### 朴素贝叶斯 鸢尾花


In [ ]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

x,y = load_iris().data,load_iris().target
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=1,test_size=50)
len(x_test)


#训练模型
model = GaussianNB()
model.fit(x_train,y_train)

#评估
pred = model.predict(x_test)
print('预测集数据的预测标签是：',pred)
print('测试机数据的真实标签是:',y_test)
acc = accuracy_score(y_test,pred)
print('预测的准确率是：',acc)
sum(pred!=y_test)

# 垃圾邮件

In [1]:
import os 
normalFileList = os.listdir('../bayes/normal')
spamFileList = os.listdir('../bayes/spam')
print('正常邮件列表为：',normalFileList)
print('垃圾邮件列表为：',spamFileList)

正常邮件列表为： ['normal-mail1.txt', 'normal-mail2.txt', 'normal-mail3.txt', 'normal-mail4.txt', 'normal-mail5.txt', 'normal-mail6.txt', 'normal-mail7.txt', 'normal-mail8.txt', 'normal-mail9.txt']
垃圾邮件列表为： ['spam-mail1.txt', 'spam-mail2.txt', 'spam-mail3.txt', 'spam-mail4.txt', 'spam-mail5.txt', 'spam-mail6.txt', 'spam-mail7.txt', 'spam-mail8.txt', 'spam-mail9.txt']


In [4]:
stopList = []
for line in open('../bayes/stopwords.txt','r',encoding='utf-8'):
    stopList.append(line[:len(line) - 1])
print(stopList)

['啊', '阿', '哎', '哎呀', '唉', '于是', '还']


In [5]:
from jieba import cut
from re import sub

def getWord(file,stopList):
    wordslist = []
    for line in open(file,encoding='utf-8'):
        line = line.strip()
        line = sub(r'[.【】0-9、——，。！\~*]','',line)
        line = cut(line)
        line = filter(lambda word:len(word) > 1,line)
        wordslist.extend(line)
        words = []
        for i in wordslist:
            if i not in stopList and i.strip() != '' and i != None:
                words.append(i)
                
    return words
        

In [7]:
from collections import Counter
from itertools import chain

allwords = []
for normalfile in normalFileList:
    words = getWord('../bayes/normal/'+normalfile,stopList)
    allwords.append(words)
for spamfile in spamFileList:
    words = getWord('../bayes/spam/'+spamfile,stopList)
    allwords.append(words)
print('训练集中所有的有效词语列表：',allwords)

Building prefix dict from the default dictionary ...
Dumping model to file cache C:\Users\33079\AppData\Local\Temp\jieba.cache
Loading model cost 0.803 seconds.
Prefix dict has been built successfully.


训练集中所有的有效词语列表： [['张老师', '您好', '上次', '推荐', '资料', '来说', '帮助', '很大', '希望', '推荐', '一些', '资料', '非常感谢'], ['小李', '你好', '论文', '需要', '修改', '具体', '修改意见', '附件', '查收'], ['李老师', '您好', '论文', '已经', '修改', '修改', '完成', '内容', '附件', '查收'], ['小李', '你好', '论文', '需要', '修改', '具体', '修改意见', '附件', '查收'], ['小张', '你好', '论文', '需要', '修改', '具体', '修改意见', '附件', '查收'], ['张老师', '您好', '论文', '修改', '具体内容', '附件', '查收'], ['李老师', '你好', '论文', '修改', '中等', '修改', '完成', '沟通'], ['小张', '你好', '论文', '需要', '修改', '具体', '修改意见', '附件', '查收'], ['小张', '你好', '论文', '需要', '修改', '具体', '修改意见', '附件', '查收'], ['期刊', '主要', '栏目', '技术', '应用', '投稿', '邮箱', 'xx', 'com'], ['期刊', '主要', '栏目', '数据', '投稿', '邮箱', 'xx', 'com'], ['某某', '期刊', '主要', '栏目', '数据', '投稿', '邮箱', 'xx', 'com'], ['期刊', '主要', '栏目', '计算', '投稿', '邮箱', 'xx', 'com'], ['期刊', '主要', '栏目', '人工智能', '投稿', '邮箱', 'xx', 'com'], ['期刊', '主要', '栏目', '网络设备', '投稿', '邮箱', 'xx', 'com'], ['期刊', '主要', '栏目', '计算机', '基础', '投稿', '邮箱', 'xx', 'com'], ['期刊', '主要', '栏目', '网络', '制图', '投稿', '邮箱', 'xx', 'com'], ['期刊', '主要', 

In [12]:
frep = Counter(chain(*allwords))
topTen = frep.most_common(10)
topTen
topWords = [i[0] for i in topTen]
print('训练集中出现频率最高的10个词语是：',topWords)


训练集中出现频率最高的10个词语是： ['修改', '期刊', '主要', '栏目', '投稿', '邮箱', 'xx', 'com', '论文', '附件']


In [13]:
import numpy as np
vector = []
for words in allwords:
    temp = list(map(lambda x:words.count(x),topWords))
    vector.append(temp)
vector = np.array(vector)
print('10个高频词语在每封邮件中出现的次数：\n',vector)

10个高频词语在每封邮件中出现的次数：
 [[0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 1 1]
 [2 0 0 0 0 0 0 0 1 1]
 [1 0 0 0 0 0 0 0 1 1]
 [1 0 0 0 0 0 0 0 1 1]
 [1 0 0 0 0 0 0 0 1 1]
 [2 0 0 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 0 1 1]
 [1 0 0 0 0 0 0 0 1 1]
 [0 1 1 1 1 1 1 1 0 0]
 [0 1 1 1 1 1 1 1 0 0]
 [0 1 1 1 1 1 1 1 0 0]
 [0 1 1 1 1 1 1 1 0 0]
 [0 1 1 1 1 1 1 1 0 0]
 [0 1 1 1 1 1 1 1 0 0]
 [0 1 1 1 1 1 1 1 0 0]
 [0 1 1 1 1 1 1 1 0 0]
 [0 1 1 1 1 1 1 1 0 0]]


In [14]:
from sklearn.naive_bayes import MultinomialNB

target = np.array([0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1])

x,y = vector,target
model = MultinomialNB()
model.fit(x,y)


MultinomialNB()

In [15]:
test = os.listdir('../bayes/test')
for testFile in test:
    words = getWord('../bayes/test/'+testFile,stopList)
    test_x = np.array(tuple(map(lambda word:words.count(word),topWords)))
    result = model.predict(test_x.reshape(1,-1))
    if result == 1:
        print(testFile,'为垃圾邮件')
    else:
        print(testFile,'为正常邮件')

normal-test.txt 为正常邮件
spam-test.txt 为垃圾邮件
